path = {                                                              # chatgpt_data_source/astrobot
               "Airflow Version Update":"https://github.ford.com/cmsa/Astronomer/wiki/Airflow-Version-Update", 
               "Astro_Faq's":"https://github.ford.com/cmsa/Astronomer/wiki/Astro_Faq's",
               "Astro Top 30 FAQs":"https://github.ford.com/cmsa/Astronomer/wiki/Astro-Top-30-FAQs",
               "Astronomer Best Practices Suggested by Astronomer Support": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Best-Practices----Suggested-by-Astronomer-Support",
               "Astronomer CI Pipeline Issues and Troubleshooting": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-CI-Pipeline-Issues-and-Troubleshooting", 
               "Astronomer Local Dev Setup":"https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Local-Dev-Setup",
               "Astronomer Platform Architecture": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer--Platform-Architecture",
               "Astronomer Proxy IDs": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Proxy-IDs",
               "Astronomer Service links with purpose":"https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Service-links-with-purpose",
               "Astronomer Webex Groups": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Webex-Groups",
               "CMSA_Astronomer_APIGEE API Details":"https://github.ford.com/cmsa/Astronomer/wiki/CMSA_Astronomer_APIGEE-API-Details",
               "Clearing the stuck clean up jobs": "https://github.ford.com/cmsa/Astronomer/wiki/Clearing-the-stuck-clean-up-jobs",
               "Cronjobs": "https://github.ford.com/cmsa/Astronomer/wiki/Cronjobs",
               "FIM Groups for Astronomer": "https://github.ford.com/cmsa/Astronomer/wiki/FIM-Groups-for-Astronomer",
               "GCP MQL Query Commands for GKE Clusters": "https://github.ford.com/cmsa/Astronomer/wiki/GCP-MQL-Query-Commands-for-GKE-Clusters",
               
                                                                    # chatgpt_data_source/Astrodoc
               "Airflow API": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Airflow-API",
               "Airflow Notifications & Alerting": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/airflow-alerting", 
               "Airflow Packages": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/airflow-image-packages-install", 
               "Astro GCP Connections": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-gcp-connections/",
               "Astro Logging Pubsub Preprod": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-logging-pubsub/preprod/Readm", 
               "Astro Logging Pubsub Prod": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-logging-pubsub/prod/Readme/", 
               "Astro Runtime Customer Doc": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-runtime-customer-doc/Readme", 
               "Astronomer Contact": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer-contact/" , 
               "Astronomer FAQs": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer-FAQs/", 
               "Astronomer IT Connect": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer-IT_connect/", 
               "Astronomer RBAC": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer%20RBAC", 
               "Astro Docs Training query": "https://pages.github.ford.com/gcam/astronomer-docs/",
               "Email Relay":"https://pages.github.ford.com/gcam/astronomer-docs/astronomer/email-relay",
               "External Secrets Backend": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro_external_secrets_backend",
               "Exception Based Services": "https://docs.gcp.ford.com/docs/onboard/exception-based-services",
               "Home": "https://pages.github.ford.com/gcam/astronomer-docs/", 
               "Local Dev Setup": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-localdev",
               "Sample Dag and Variables Connections": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-variables-connections", 
               "Starting with Airflow":"https://pages.github.ford.com/gcam/astronomer-docs/airflow-getting-started/",
               "Starting with Astronomer": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-onboarding" , 
               "Tekton CI Tasks":"https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-ci-doc",

                                                                 # chatgpt_data_source/gcp_docs
               "2.0 Migration Overview": "https://docs.gcp.ford.com/docs/support/migration/migration/",
               "2.0 Migration": "https://docs.gcp.ford.com/docs/support/migration/",

               "ADFS Workload Identity Federation (WIF) Guide": "https://docs.gcp.ford.com/docs/support/authentication/adfs-wif-guide/",
               "AlloyDB for PostgreSQL (alloydb)": "https://docs.gcp.ford.com/docs/services/database/alloydb/",
               "Analytic Hub (hub)": "https://docs.gcp.ford.com/docs/services/analytics/hub/",
               "analytics": "https://docs.gcp.ford.com/docs/services/analytics/",
               "Anthos Bare Metal (anthosbm)": "https://docs.gcp.ford.com/docs/services/cloud/anthosbm/",
               "Anthos Service Mesh (anthossm)": "https://docs.gcp.ford.com/docs/services/cloud/anthossm/",
               "Application Load Balancer (applb)": "https://docs.gcp.ford.com/docs/services/network/applb/",
               "Astronomer : Airflow (astronomer)": "https://docs.gcp.ford.com/docs/services/analytics/astronomer/",
               "Assisted Migration": "https://docs.gcp.ford.com/docs/support/migration/assisted-migration/",
               "Authentication (gcloud CLI)": "https://docs.gcp.ford.com/docs/support/authentication/gcloud/",
               "Authentication": "https://docs.gcp.ford.com/docs/support/authentication/",
               "Auto ML (automl)": "https://docs.gcp.ford.com/docs/services/machine-learning/automl/",
               
               "Batch (batch)":"https://docs.gcp.ford.com/docs/services/compute/batch/",
               "BigQuery ML (bigqml)":"https://docs.gcp.ford.com/docs/services/analytics/bigqml/",
               "BigQuery (bigq)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/bigq/",
               "BigQuery Connection (bigqconn)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/bigqconn/",
               "BigQuery Data Transfer (bigqdatatr)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/bigqdatatr/",
               "Binary Authorization (binauth)":"https://docs.gcp.ford.com/docs/services/dev-tools/binauth/",
               
               "Cloud : AI Video (videoai)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/videoai/",
               "Cloud : AI Vision (visionai)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/visionai/",
               "Cloud Advocate Support": "https://docs.gcp.ford.com/docs/support/cloud-advocate-support/",
               "Cloud Bigtable (bigtbl)": "https://docs.gcp.ford.com/docs/services/database/bigtbl/",
               "Cloud Billing (cldbill)":"https://docs.gcp.ford.com/docs/services/cloud/cldbill/",
               "Cloud CDN (cldcdn)":"https://docs.gcp.ford.com/docs/services/cloud/cldcdn/",
               "Cloud DNS (clddns)":"https://docs.gcp.ford.com/docs/services/network/clddns/",
               "Cloud DNS GSLB (clddnsgslb)":"https://docs.gcp.ford.com/docs/services/network/clddnsgslb/",
               "Cloud Firestore (firestore)": "https://docs.gcp.ford.com/docs/services/database/firestore/",
               "Cloud interconnect (cldic)":"https://docs.gcp.ford.com/docs/services/network/cldic/",
               "Cloud Load Balancing (cldlb)":"https://docs.gcp.ford.com/docs/services/network/cldlb/",
               "Cloud Source Repositories (cldsr)":"https://docs.gcp.ford.com/docs/services/cloud/cldsr/",
               "Cloud Spanner (cldspanner)":"https://docs.gcp.ford.com/docs/services/database/cldspanner/",
               "Cloud SQL - MySQL Server (mysql)":"https://docs.gcp.ford.com/docs/services/database/mysql/",
               "Cloud SQL for Postgres SQL (psql)":"https://docs.gcp.ford.com/docs/services/database/psql/",
               "Cloud SQL for SQL Server (cldsql)":"https://docs.gcp.ford.com/docs/services/database/cldsql/",
               "Cloud Tasks (cldtasks)":"https://docs.gcp.ford.com/docs/services/developer-tools/cldtasks/",
               "Cloud VPN (cldvpn)":"https://docs.gcp.ford.com/docs/services/network/cldvpn/",
               "Cloud Workstations (cldws)":"https://docs.gcp.ford.com/docs/services/compute/cldws/",
               "Confluent Kafka Platform (kafka)":"https://docs.gcp.ford.com/docs/services/messaging-middleware/kafka/",
               "Cloud Natural Language API (cldnlng)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/cldnlng/",
               "Cloud Network Delivery Overview": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cloud-network-delivery-overview/",
               "Cloud Network Delivery Team Owned Terraform": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cnd-owned-terraform/",
               "Cloud Network Delivery": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/",
               "Cloud Network Developer View": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cnd-developer-view/",
               "Cloud Network Support": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cloud-network-support/",
               "Communication Channels": "https://docs.gcp.ford.com/docs/support/gcp-communication-channels/",
               "Configuring GKE WIF": "https://docs.gcp.ford.com/docs/support/authentication/gke/",
               "Configuring OpenShift WIF for Sandbox and Dev (Local Dev) GCP Project": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-lower-envs/",
               "Configuring OpenShift WIF for upper environment GCP projects (e.g. Prod, QA, etc.)": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-upper-envs/",
               "Configuring OpenShift WIF": "https://docs.gcp.ford.com/docs/support/authentication/oc/",
               "Create OpenShift Secret": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-create-secret/",
               "Create OpenShift WIF Service using Bash Commands":"https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-bash-cmd/",

               "Data Catalog (datacat)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/datacat/",
               "Data Fusion (datafusion)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/datafusion/",
               "Data Lineage (datalineage)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/datalineage/",
               "Data Plex (dataplex)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/dataplex/",
               "DataFlow (dataflow)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/dataflow/",
               "Dataflow Job Migration to a 2.0 Project":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/dataflow/migration/",
               "Dataproc (Spark) (dataproc)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/dataproc/",
               "Delete Namespace Resources": "https://docs.gcp.ford.com/docs/support/tekton/delete-namespace-resources/",
               "Dialogflow (dialogflow)":"https://docs.gcp.ford.com/docs/services/machine-learning/dialogflow/",
               "Data Prep (dataprep)":"https://docs.gcp.ford.com/docs/services/analytics/dataprep/",
               "Document AI (Human-in-the-loop AI) (docai)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/docai/",
               "Documentation": "https://docs.gcp.ford.com/docs/",
               "Dora": "https://docs.gcp.ford.com/docs/onboard/dora/",

               "Eventarc (eventarc)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/eventarc/",
               "External Cloud Run (extcldrun)":"https://docs.gcp.ford.com/docs/services/external-facing/extcldrun/",
               "External Cloud Storage (extgcs)":"https://docs.gcp.ford.com/docs/services/external-facing/extgcs/",
               "External Data Transfer (extsts)":"https://docs.gcp.ford.com/docs/services/external-facing/extsts/",
               "EAMS Application ID": "https://docs.gcp.ford.com/docs/support/eams-id/",
               "Environments": "https://docs.gcp.ford.com/docs/onboard/projects/environment/",
               "Exception-Based Services": "https://docs.gcp.ford.com/docs/onboard/exception-based-services/",

               "FAQ":"https://docs.gcp.ford.com/docs/faq/",
               "Ford GCP IAM Architecture": "https://docs.gcp.ford.com/docs/onboard/gcp-iam-architecture/",
               "Ford Cloud Portal IaC Prerequisites": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/fcp-iac-prereqs/",
               "Ford Cloud Portal Instructions": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/",
               "Ford GCP vs Native Google Experience": "https://docs.gcp.ford.com/docs/onboard/ford-gcp/",

           

               "GCP Authentication Methods in the Ford GCP Tenant": "https://docs.gcp.ford.com/docs/onboard/gcp-auth-methods/",
               "GCP External Project Tile Instructions": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/gcp-external/",
               "GCP Project Quotas": "https://docs.gcp.ford.com/docs/support/quota/about-quotas/",
               "GCP Regions": "https://docs.gcp.ford.com/docs/support/gcp-regions/",
               "GCP Services Decision Point Guide for Architects": "https://docs.gcp.ford.com/docs/support/gcp-services-guide/",
               "GCP Services: SRE Engineer Roles and Responsibilities": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/gcp-monitoring-roles/",
               "GCP Project Bundles": "https://docs.gcp.ford.com/docs/onboard/projects/bundles/",
               "GCP Project Proxy Settings": "https://docs.gcp.ford.com/docs/onboard/projects/proxy/", 
               "GCP Project Structure": "https://docs.gcp.ford.com/docs/onboard/projects/structure/",
               "GCP Project Updates": "https://docs.gcp.ford.com/docs/onboard/projects/updates/",
               "GCP Standard Project Tile Instructions": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/gcp-standard/",
               "Getting Started with Tekton Namespace": "https://docs.gcp.ford.com/docs/support/tekton/namespace/",
               "Getting Started": "https://docs.gcp.ford.com/docs/onboard/getting-started/",
               "GitHub SSH and Personal Access Tokens": "https://docs.gcp.ford.com/docs/onboard/github-ssh-and-token-configuration/",
               "Guidance for Module Consumers": "https://docs.gcp.ford.com/docs/support/terraform/module-consumers/",
               "Guidance for Module Owners": "https://docs.gcp.ford.com/docs/support/terraform/module-owners/",
               "Guide to the Ford GCP Environment": "https://docs.gcp.ford.com/docs/onboard/gcp-overview/",
               "Generative AI App Builder (genaiab)":"https://docs.gcp.ford.com/docs/services/machine-learning/genaiab/",
               "Global External Load Balancer (gxlbpscneg)":"https://docs.gcp.ford.com/docs/services/external-facing/gxlbpscneg/",
               "Global Load Balancer (gxlb)":"https://docs.gcp.ford.com/docs/services/network/gxlb/",

               "How to Gain Access to Dynatrace Dashboard": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/dynatrace-access/",
               "How to Handle Active Outages": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/dynatrace-outage-procedure/",

               "ITO Service Readiness Checklist for Service Owners": "https://docs.gcp.ford.com/docs/support/service-readiness-checklist/",
               "IaC and Pipeline standards": "https://docs.gcp.ford.com/docs/onboard/iac-pipeline-standards/",
               "In-house Terraform modules": "https://docs.gcp.ford.com/docs/support/terraform/modules-guidance/",
               "Image Creation (gceimg)":"https://docs.gcp.ford.com/docs/services/compute-engine/gceimg/",
               "Immersive Stream for XR (immedge)":"https://docs.gcp.ford.com/docs/services/compute/immedge/",
               "Instance - Virtual Machine (gce)":"https://docs.gcp.ford.com/docs/services/compute-engine/gce/",
               "Instance Groups (mig)":"https://docs.gcp.ford.com/docs/services/compute-engine/mig/",

               "Jupyter notebooks (jupyter)":"https://docs.gcp.ford.com/docs/services/hpc----ai-platform/jupyter/",

               "Live Stream API (livestream)": "https://docs.gcp.ford.com/docs/services/developer-tools/livestream/",

               "Managed Pipeline": "https://docs.gcp.ford.com/docs/support/tekton/managed-pipeline/",
               "Manual Self-Migration": "https://docs.gcp.ford.com/docs/support/migration/self-migration/",
               "Manually Edit tfstate Files": "https://docs.gcp.ford.com/docs/support/terraform/manually-edit-tfstate-file/",
               "Monitoring Quota": "https://docs.gcp.ford.com/docs/support/quota/alert-policy/",
               "Monitoring": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/",
               "MemoryStore for Redis (memstore)":"https://docs.gcp.ford.com/docs/services/database/memstore/",
               "MongoDB Atlas (mongo)":"https://docs.gcp.ford.com/docs/services/database/mongo/",

               "On-Call Mock Drill Procedure": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/on-call-training-and-mock-drill-procedures/",
               "Onboarding Changes": "https://docs.gcp.ford.com/docs/onboard/changelog/",
               "Onboarding": "https://docs.gcp.ford.com/docs/onboard/",
               "OpenShift": "https://docs.gcp.ford.com/docs/support/authentication/openshift/",
               "Overview": "https://docs.gcp.ford.com/docs/overview/",

               "Policy as Code": "https://docs.gcp.ford.com/docs/onboard/policy-as-code/",
               "Project Details Reference Table": "https://docs.gcp.ford.com/docs/onboard/projects/", 
               "Permission (IAM)": "https://docs.gcp.ford.com/docs/support/permission/",
               "Project Provisioning": "https://docs.gcp.ford.com/docs/onboard/projects/",
               "Private Service Connect Network Endpoint Groups (pscneg)":"https://docs.gcp.ford.com/docs/services/compute/pscneg/",
               "Pub:Sub (pubsub)":"https://docs.gcp.ford.com/docs/services/ai---ml---analytics/pubsub/",

               "Quotas & Management": "https://docs.gcp.ford.com/docs/support/quota/",

               "Red Hat OpenShift Dev Spaces Examples": "https://docs.gcp.ford.com/docs/support/devspaces/examples/",
               "Red Hat OpenShift Dev Spaces Overview": "https://docs.gcp.ford.com/docs/support/devspaces/overview/",
               "Red Hat OpenShift Dev Spaces devfile": "https://docs.gcp.ford.com/docs/support/devspaces/devfile/",
               "Red Hat OpenShift Dev Spaces": "https://docs.gcp.ford.com/docs/support/devspaces/",
               "Reduce Outage Disruption Hours": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/reduce-outage-bfm/",

               "SCC Escalation Matrix": "https://docs.gcp.ford.com/docs/support/security/esc-matrix/",
               "Security Category Focusing": "https://docs.gcp.ford.com/docs/support/security/security-category-focusing/",
               "Security": "https://docs.gcp.ford.com/categories/security/",
               "Security Considerations": "https://docs.gcp.ford.com/docs/onboard/security-considerations/",
               "Security Groups": "https://docs.gcp.ford.com/docs/onboard/security-groups/",
               "Self-Service": "https://docs.gcp.ford.com/docs/support/gcp-self-service/",
               "Self-Service Manually Provisioned Services": "https://docs.gcp.ford.com/docs/onboard/self-service-manually-provisioned/",
               "Service Account": "https://docs.gcp.ford.com/docs/support/service-account/",
               "Speech-to-Text API (stt)":"https://docs.gcp.ford.com/docs/services/machine-learning/stt/",
               "Support Channels": "https://docs.gcp.ford.com/docs/support/gcp-support-channels/",
               "Support Workflow": "https://docs.gcp.ford.com/docs/support/support-workflow/",

               "Text-to-Speech API (tts)":"https://docs.gcp.ford.com/docs/services/machine-learning/tts/",
               "Tekton Overview": "https://docs.gcp.ford.com/docs/support/tekton/tekton-overview/",
               "Tekton": "https://docs.gcp.ford.com/docs/support/tekton/",
               "Terraform Example": "https://docs.gcp.ford.com/docs/support/terraform/example/",
               "Terraform Scaffolding": "https://docs.gcp.ford.com/docs/support/terraform/scaffolding/",
               "Terraform Troubleshooting and FAQ": "https://docs.gcp.ford.com/docs/support/terraform/troubleshooting-and-faq/",
               "Terraform": "https://docs.gcp.ford.com/docs/support/terraform/",
               "Test OpenShift WIF Configuration": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-test/",
               "The Art Of SLI, SLO and SLA": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/sli-slo-concepts/",

               "Understanding the Ford GCP Pipeline and Developer Service Accounts": "https://docs.gcp.ford.com/docs/support/understand-dev-account/",

               "Vault": "https://docs.gcp.ford.com/docs/support/authentication/vault/",
               "Vertex AI (vertexai)": "https://docs.gcp.ford.com/docs/services/machine-learning/vertexai/",

               "WIF CLI": "https://docs.gcp.ford.com/docs/support/authentication/wif-how-to/",   
               "Workflows (cldworkflw)":"https://docs.gcp.ford.com/docs/services/compute/cldworkflw/",
               
               "Zonal Network Endpoint Group (gcelb)": "https://docs.gcp.ford.com/docs/services/compute-engine/gcelb/",  
               
                                                                 #Apigee_Docs
               "ADFS - Enterprise API Wiki": "https://www.eesewiki.ford.com/display/FEAPIS/ADFS",
               "API Design, Standards, and Quality": "https://www.eesewiki.ford.com/display/FEAPIS/API+Design%2C+Standards%2C+and+Quality",
               "API Gateway Migration":"https://www.eesewiki.ford.com/display/FEAPIS/API+Gateway+Migration",
               "API Intentional Design Reviews":"https://www.eesewiki.ford.com/display/FEAPIS/API+Intentional+Design+Reviews",
               "API Learning":"https://www.eesewiki.ford.com/display/FEAPIS/API+Learning",
               "API Metrics and Dashboards":"https://www.eesewiki.ford.com/display/FEAPIS/API+Metrics+and+Dashboards",
               "API Operations - Troubleshooting":"https://www.eesewiki.ford.com/display/FEAPIS/API+Operations+-+Troubleshooting",
               "API Publishing Troubleshooting":"https://www.eesewiki.ford.com/display/FEAPIS/API+Publishing+Troubleshooting",
               "API Runtime Troubleshooting":"https://www.eesewiki.ford.com/display/FEAPIS/API+Runtime+Troubleshooting",
               "API Support & Troubleshooting":"https://www.eesewiki.ford.com/pages/viewpage.action?pageId=1005400337",
               "APIM":"https://www.eesewiki.ford.com/display/FEAPIS/APIM",
               "Apigee":"https://www.eesewiki.ford.com/display/FEAPIS/Apigee",
               "Apigee API Publisher":"https://www.eesewiki.ford.com/display/FEAPIS/Apigee+API+Publisher",
               "Azure AD Permissions":"https://www.eesewiki.ford.com/display/FEAPIS/Azure+AD+Permissions",
               "China APIM":"https://www.eesewiki.ford.com/display/FEAPIS/China+APIM", 
               "Complete Setup in API Catalog":"https://www.eesewiki.ford.com/display/FEAPIS/Complete+Setup+in+API+Catalog",
               "Configure API Security":"https://www.eesewiki.ford.com/display/FEAPIS/Configure+API+Security",
               "Connect with Us":"https://www.eesewiki.ford.com/display/FEAPIS/Connect+with+Us",
               "Disaster Recovery":"https://www.eesewiki.ford.com/display/FEAPIS/Disaster+Recovery+-+NA",
               "Enterprise API Standards":"https://www.eesewiki.ford.com/display/FEAPIS/Enterprise+API+Standards",
               "Ford Advisory Management (FAM) Usage":"https://www.eesewiki.ford.com/display/FEAPIS/Ford+Advisory+Management+%28FAM%29+Usage",
               "Ford Enterprise API Strategy":"",
               "Ford POV on Data Models":"https://www.eesewiki.ford.com/display/FEAPIS/Ford+POV+on+Data+Models",
               "Ford REST API Linter":"https://www.eesewiki.ford.com/display/FEAPIS/Ford+REST+API+Linter",
               "Gateway, App and API Troubleshooting Tips":"https://www.eesewiki.ford.com/display/FEAPIS/Gateway%2C+App+and+API+Troubleshooting+Tips",
               "Google Cloud Load Balancer (GLB)":"https://www.eesewiki.ford.com/pages/viewpage.action?pageId=903317751",
               "Granting Access":"https://www.eesewiki.ford.com/display/FEAPIS/Granting+Access",
               "Intentional API Design":"https://www.eesewiki.ford.com/display/FEAPIS/Intentional+API+Design",
               "Intentional Design Example":"https://www.eesewiki.ford.com/display/FEAPIS/Intentional+Design+Example",
               "Journey Maps":"https://www.eesewiki.ford.com/display/FEAPIS/Journey+Maps",
               "Key Aspects of API Design":"https://www.eesewiki.ford.com/display/FEAPIS/Key+Aspects+of+API+Design",
               "Migrating from APIM-TOKEN to mTLS":"https://www.eesewiki.ford.com/pages/viewpage.action?pageId=1163199693",
               "Migration Support":"https://www.eesewiki.ford.com/display/FEAPIS/Migration+Support",
               "NA APIM (Deprecated)":"https://www.eesewiki.ford.com/pages/viewpage.action?pageId=910235373",
               "Open API:Swagger Specification":"https://www.eesewiki.ford.com/pages/viewpage.action?pageId=892457488",
               "Publish API":"https://www.eesewiki.ford.com/display/FEAPIS/Publish+API",
               "Publisher Secret Expiration Info":"https://www.eesewiki.ford.com/display/FEAPIS/Publisher+Secret+Expiration+Info",
               "Register a new API":"https://www.eesewiki.ford.com/display/FEAPIS/Register+a+new+API",
               "Self-Help Design Review Guide":"https://www.eesewiki.ford.com/display/FEAPIS/Self-Help+Design+Review+Guide",
               "Style Guides":"https://www.eesewiki.ford.com/display/FEAPIS/Style+Guides",

          }


