path = { "Airflow Version Update":"https://github.ford.com/cmsa/Astronomer/wiki/Airflow-Version-Update", "Astro_Faq's":"https://github.ford.com/cmsa/Astronomer/wiki/Astro_Faq's", 
               "Astronomer Best Practices Suggested by Astronomer Support": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Best-Practices----Suggested-by-Astronomer-Support",
               "Astronomer CI Pipeline Issues and Troubleshooting": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-CI-Pipeline-Issues-and-Troubleshooting", 
               "Astronomer Local Dev Setup":"https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Local-Dev-Setup",
               "Astronomer Platform Architecture": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer--Platform-Architecture",
               "Astronomer Proxy IDs": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Proxy-IDs",
               "Astronomer Service links with purpose":"https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Service-links-with-purpose",
               "Astronomer Webex Groups": "https://github.ford.com/cmsa/Astronomer/wiki/Astronomer-Webex-Groups",
               "CMSA Astronomer APIGEE API Details":"https://github.ford.com/cmsa/Astronomer/wiki/CMSA_Astronomer_APIGEE-API-Details",
               "Clearing the stuck clean up jobs": "https://github.ford.com/cmsa/Astronomer/wiki/Clearing-the-stuck-clean-up-jobs",
               "Cronjobs": "https://github.ford.com/cmsa/Astronomer/wiki/Cronjobs",
               "FIM Groups for Astronomer": "https://github.ford.com/cmsa/Astronomer/wiki/FIM-Groups-for-Astronomer",
               "GCP MQL Query Commands for GKE Clusters": "https://github.ford.com/cmsa/Astronomer/wiki/GCP-MQL-Query-Commands-for-GKE-Clusters",
               ################################################################
               "Airflow API ": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Airflow-API",
               "Airflow Notifications & Alerting": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/airflow-alerting", 
               "Airflow Packages": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/airflow-image-packages-install", 
               "Astro GCP Connections": "/astronomer/astro-gcp-connections",
               "Astro Logging Pubsub Preprod": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-logging-pubsub/preprod/Readm", 
               "Astro Logging Pubsub Prod ": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-logging-pubsub/prod/Readme/", 
               "Astro Runtime Customer Doc": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-runtime-customer-doc/Readme", 
               "Astronomer Contact": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer-contact/" , 
               "Astronomer FAQs": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer-FAQs/", 
               "Astronomer IT Connect": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer-IT_connect/", 
               "Astronomer RBAC": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/Astronomer%20RBAC", 
               "Email Relay":"https://pages.github.ford.com/gcam/astronomer-docs/astronomer/email-relay",
               "External Secrets Backend": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro_external_secrets_backend",
               "Exception Based Services | GCP Docs.pdf": "https://docs.gcp.ford.com/docs/onboard/exception-based-services",
               "Home": "https://pages.github.ford.com/gcam/astronomer-docs/", "Local Dev Setup": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-localdev",
               "Local Dev Setup": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-localdev/",
               "Sample Dag and Variables Connections": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-variables-connections", 
               "Starting with Airflow":"https://pages.github.ford.com/gcam/astronomer-docs/airflow-getting-started/",
               "Starting with Astronomer": "https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-onboarding" , 
               "Tekton CI Tasks":"https://pages.github.ford.com/gcam/astronomer-docs/astronomer/astro-ci-doc",
               #GCP Docs
               "2.0 Migration Overview": "https://docs.gcp.ford.com/docs/support/migration/migration/",
               "2.0 Migration": "https://docs.gcp.ford.com/docs/support/migration/",
               "ADFS Workload Identity Federation (WIF) Guide": "https://docs.gcp.ford.com/docs/support/authentication/adfs-wif-guide/",
               "AlloyDB for PostgreSQL (alloydb)": "https://docs.gcp.ford.com/docs/services/database/alloydb/",
               "Analytic Hub (hub)": "https://docs.gcp.ford.com/docs/services/analytics/hub/",
               "analytics": "https://docs.gcp.ford.com/docs/services/analytics/",
               "Anthos Bare Metal (anthosbm) ": "https://docs.gcp.ford.com/docs/services/cloud/anthosbm/",
               "Anthos Service Mesh (anthossm)": "https://docs.gcp.ford.com/docs/services/cloud/anthossm/",
               "Application Load Balancer (applb)": "https://docs.gcp.ford.com/docs/services/network/applb/",
               "Astronomer : Airflow (astronomer)": "https://docs.gcp.ford.com/docs/services/analytics/astronomer/",
               "Assisted Migration": "https://docs.gcp.ford.com/docs/support/migration/assisted-migration/",
               "Authentication (gcloud CLI)": "https://docs.gcp.ford.com/docs/support/authentication/gcloud/",
               "Authentication": "https://docs.gcp.ford.com/docs/support/authentication/",
               "Auto ML (automl)": "https://docs.gcp.ford.com/docs/services/machine-learning/automl/",
               "Batch (batch)":"https://docs.gcp.ford.com/docs/services/compute/batch/",
               "BigQuery ML (bigqml)":"https://docs.gcp.ford.com/docs/services/analytics/bigqml/",
               "Binary Authorization (binauth)":"https://docs.gcp.ford.com/docs/services/dev-tools/binauth/",
               "Cloud Bigtable (bigtbl)": "https://docs.gcp.ford.com/docs/services/database/bigtbl/",
               "Cloud Billing (cldbill)":"https://docs.gcp.ford.com/docs/services/cloud/cldbill/",
               "Cloud CDN (cldcdn)":"https://docs.gcp.ford.com/docs/services/cloud/cldcdn/",
               "Cloud DNS (clddns)":"https://docs.gcp.ford.com/docs/services/network/clddns/",
               "Cloud DNS GSLB (clddnsgslb)":"https://docs.gcp.ford.com/docs/services/network/clddnsgslb/",

               "Cloud Advocate Support": "https://docs.gcp.ford.com/docs/support/cloud-advocate-support/",
               "Cloud Network Delivery Overview": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cloud-network-delivery-overview/",
               "Cloud Network Delivery Team Owned Terraform": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cnd-owned-terraform/",
               "Cloud Network Delivery": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/",
               "Cloud Network Developer View": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cnd-developer-view/",
               "Cloud Network Support": "https://docs.gcp.ford.com/docs/support/cloud-network-delivery/cloud-network-support/",
               "Communication Channels": "https://docs.gcp.ford.com/docs/support/gcp-communication-channels/",
               "Configuring GKE WIF": "https://docs.gcp.ford.com/docs/support/authentication/gke/",
               "Configuring OpenShift WIF for Sandbox and Dev (Local Dev) GCP Project": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-lower-envs/",
               "Configuring OpenShift WIF for upper environment GCP projects (e.g. Prod, QA, etc.)": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-upper-envs/",
               "Configuring OpenShift WIF": "https://docs.gcp.ford.com/docs/support/authentication/oc/",
               "Create OpenShift Secret": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-create-secret/",
               "Create OpenShift WIF Service using Bash Commands":"https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-bash-cmd/",
               "Delete Namespace Resources": "https://docs.gcp.ford.com/docs/support/tekton/delete-namespace-resources/",
               "Documentation": "https://docs.gcp.ford.com/docs/",
               "Dora": "https://docs.gcp.ford.com/docs/onboard/dora/",
               "EAMS Application ID": "https://docs.gcp.ford.com/docs/support/eams-id/",
               "Environments": "https://docs.gcp.ford.com/docs/onboard/projects/environment/",
               "Exception-Based Services": "https://docs.gcp.ford.com/docs/onboard/exception-based-services/",
               "FAQ":"https://docs.gcp.ford.com/docs/faq/",
               "Ford GCP IAM Architecture": "https://docs.gcp.ford.com/docs/onboard/gcp-iam-architecture/",
               "Ford Cloud Portal IaC Prerequisites": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/fcp-iac-prereqs/",
               "Ford Cloud Portal Instructions": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/",
               "Ford GCP vs Native Google Experience": "https://docs.gcp.ford.com/docs/onboard/ford-gcp/",
               "GCP Authentication Methods in the Ford GCP Tenant": "https://docs.gcp.ford.com/docs/onboard/gcp-auth-methods/",
               "GCP Project Quotas": "https://docs.gcp.ford.com/docs/support/quota/about-quotas/",
               "GCP Regions": "https://docs.gcp.ford.com/docs/support/gcp-regions/",
               "GCP Services Decision Point Guide for Architects": "https://docs.gcp.ford.com/docs/support/gcp-services-guide/",
               "GCP Services: SRE Engineer Roles and Responsibilities": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/gcp-monitoring-roles/",
               "GCP External Project Tile Instructions": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/gcp-external/",
               "GCP Project Bundles": "https://docs.gcp.ford.com/docs/onboard/projects/bundles/",
               "GCP Project Proxy Settings": "https://docs.gcp.ford.com/docs/onboard/projects/proxy/", 
               "GCP Project Structure": "https://docs.gcp.ford.com/docs/onboard/projects/structure/",
               "GCP Project Updates": "https://docs.gcp.ford.com/docs/onboard/projects/updates/",
               "GCP Standard Project Tile Instructions": "https://docs.gcp.ford.com/docs/onboard/fcp-instructions/gcp-standard/",
               "Getting Started with Tekton Namespace": "https://docs.gcp.ford.com/docs/support/tekton/namespace/",
               "Getting Started": "https://docs.gcp.ford.com/docs/onboard/getting-started/",
               "GitHub SSH and Personal Access Tokens": "https://docs.gcp.ford.com/docs/onboard/github-ssh-and-token-configuration/",
               "Guidance for Module Consumers": "https://docs.gcp.ford.com/docs/support/terraform/module-consumers/",
               "Guidance for Module Owners": "https://docs.gcp.ford.com/docs/support/terraform/module-owners/",
               "Guide to the Ford GCP Environment": "https://docs.gcp.ford.com/docs/onboard/gcp-overview/",
               "How to Gain Access to Dynatrace Dashboard": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/dynatrace-access/",
               "How to Handle Active Outages": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/dynatrace-outage-procedure/",
               "ITO Service Readiness Checklist for Service Owners": "https://docs.gcp.ford.com/docs/support/service-readiness-checklist/",
               "IaC and Pipeline standards": "https://docs.gcp.ford.com/docs/onboard/iac-pipeline-standards/",
               "In-house Terraform modules": "https://docs.gcp.ford.com/docs/support/terraform/modules-guidance/",
               "Managed Pipeline": "https://docs.gcp.ford.com/docs/support/tekton/managed-pipeline/",
               "Manual Self-Migration": "https://docs.gcp.ford.com/docs/support/migration/self-migration/",
               "Manually Edit tfstate Files": "https://docs.gcp.ford.com/docs/support/terraform/manually-edit-tfstate-file/",
               "Monitoring Quota": "https://docs.gcp.ford.com/docs/support/quota/alert-policy/",
               "Monitoring": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/",
               "On-Call Mock Drill Procedure": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/on-call-training-and-mock-drill-procedures/",
               "Onboarding Changes": "https://docs.gcp.ford.com/docs/onboard/changelog/",
               "Onboarding": "https://docs.gcp.ford.com/docs/onboard/",
               "OpenShift": "https://docs.gcp.ford.com/docs/support/authentication/openshift/",
               "Overview": "https://docs.gcp.ford.com/docs/overview/",
               "Policy as Code": "https://docs.gcp.ford.com/docs/onboard/policy-as-code/",
               "Project Details Reference Table": "https://docs.gcp.ford.com/docs/onboard/projects/", 
               "Permission (IAM)": "https://docs.gcp.ford.com/docs/support/permission/",
               "Project Provisioning": "https://docs.gcp.ford.com/docs/onboard/projects/",
               "Quotas & Management": "https://docs.gcp.ford.com/docs/support/quota/",
               "Red Hat OpenShift Dev Spaces Examples": "https://docs.gcp.ford.com/docs/support/devspaces/examples/",
               "Red Hat OpenShift Dev Spaces Overview": "https://docs.gcp.ford.com/docs/support/devspaces/overview/",
               "Red Hat OpenShift Dev Spaces devfile": "https://docs.gcp.ford.com/docs/support/devspaces/devfile/",
               "Red Hat OpenShift Dev Spaces": "https://docs.gcp.ford.com/docs/support/devspaces/",
               "Reduce Outage Disruption Hours": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/reduce-outage-bfm/",
               "SCC Escalation Matrix": "https://docs.gcp.ford.com/docs/support/security/esc-matrix/",
               "Security Category Focusing": "https://docs.gcp.ford.com/docs/support/security/security-category-focusing/",
               "Security": "https://docs.gcp.ford.com/categories/security/",
               "Security Considerations": "https://docs.gcp.ford.com/docs/onboard/security-considerations/",
               "Security Groups": "https://docs.gcp.ford.com/docs/onboard/security-groups/",
               "Self-Service": "https://docs.gcp.ford.com/docs/support/gcp-self-service/",
               "Self-Service Manually Provisioned Services": "https://docs.gcp.ford.com/docs/onboard/self-service-manually-provisioned/",
               "Service Account": "https://docs.gcp.ford.com/docs/support/service-account/",
               "Support Channels": "https://docs.gcp.ford.com/docs/support/gcp-support-channels/",
               "Support Workflow": "https://docs.gcp.ford.com/docs/support/support-workflow/",
               "Tekton Overview": "https://docs.gcp.ford.com/docs/support/tekton/tekton-overview/",
               "Tekton": "https://docs.gcp.ford.com/docs/support/tekton/",
               "Terraform Example": "https://docs.gcp.ford.com/docs/support/terraform/example/",
               "Terraform Scaffolding": "https://docs.gcp.ford.com/docs/support/terraform/scaffolding/",
               "Terraform Troubleshooting and FAQ": "https://docs.gcp.ford.com/docs/support/terraform/troubleshooting-and-faq/",
               "Terraform": "https://docs.gcp.ford.com/docs/support/terraform/",
               "Test OpenShift WIF Configuration": "https://docs.gcp.ford.com/docs/support/authentication/oc/openshift-test/",
               "The Art Of SLI, SLO and SLA": "https://docs.gcp.ford.com/docs/support/cloud-monitoring/sli-slo-concepts/",
               "Understanding the Ford GCP Pipeline and Developer Service Accounts": "https://docs.gcp.ford.com/docs/support/understand-dev-account/",
               "Vault": "https://docs.gcp.ford.com/docs/support/authentication/vault/",
               "Vertex AI (vertexai)": "https://docs.gcp.ford.com/docs/services/machine-learning/vertexai/",
               "WIF CLI": "https://docs.gcp.ford.com/docs/support/authentication/wif-how-to/",   
               "Workflows (cldworkflw)":"https://docs.gcp.ford.com/docs/services/compute/cldworkflw/",
               "Zonal Network Endpoint Group (gcelb)": "https://docs.gcp.ford.com/docs/services/compute-engine/gcelb/"   
               
          }


